export const CREATE_PCB = 'CREATE_PCB';
export const CREATE_PCB_SUCCESS = 'CREATE_PCB_SUCCESS';
export const CREATE_PCB_FAILURE = 'CREATE_PCB_FAILURE';

export const GET_PCBS = 'GET_PCBS';
export const GET_PCBS_SUCCESS = 'GET_PCBS_SUCCESS';
export const GET_PCBS_FAILURE = 'GET_PCBS_FAILURE';

export const GET_PCB_BY_ID = 'GET_PCB_BY_ID';
export const GET_PCB_BY_ID_SUCCESS = 'GET_PCB_BY_ID_SUCCESS';
export const GET_PCB_BY_ID_FAILURE = 'GET_PCB_BY_ID_FAILURE';

export const UPDATE_PCB = 'UPDATE_PCB';
export const UPDATE_PCB_SUCCESS = 'UPDATE_PCB_SUCCESS';
export const UPDATE_PCB_FAILURE = 'UPDATE_PCB_FAILURE';

export const DELETE_PCB = 'DELETE_PCB';
export const DELETE_PCB_SUCCESS = 'DELETE_PCB_SUCCESS';
export const DELETE_PCB_FAILURE = 'DELETE_PCB_FAILURE';

export const RESET_UPDATE_SUCCESS = 'RESET_UPDATE_SUCCESS';
